title: A Security Academic in Qatar
author: Ryan Riley
#baseurl: "/~rdriley" # the subpath of your site, e.g. /blog
#url: "https://www.cs.cmu.edu" # the base hostname & protocol for your site, e.g. http://example.com
